"use strict";
let areEnjoying = "true";
let rides = areEnjoying ? "Rollercoaster" : "Droptower";
console.log(rides);
let yourAge = 21;
let b = yourAge >= 21 ? "you are allowed" : "you are not allowed";
console.log(b);
let bestMemorableDay = "false";
let day = bestMemorableDay ? "first day of school" : "picnic at seaside";
console.log(day);
let teaTime = "true";
let snacks = teaTime ? "biscuits" : "tea";
console.log(snacks);
let weather = "true";
let hotDay = weather ? "stay hydrated" : "stay in door";
console.log(hotDay);
